spring:
  datasource:
    url: jdbc:h2:mem:database

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    ddl-auto: create-drop
    defer-datasource-initialization: true


